### ISSUE TITLE
Create a view that contains a form for updating current book selected from the search view

### ISSUE THREAD

**Issue by MarceStarlet** [MarceStarlet/mongodb-basics#2]
Once the user have selected a book to update it, a new page/modal is loaded with the book data pre-loaded on each field.

- Create a new html file or modal using bootstrap default theme.
- Add and HTML form (bootstrap theme) that requests an update from the user the following pre-loaded data from the book selected on the search view:
    - ISBN
    - Title
    - Description
    - Edition
    - Editorial
    - Author(s) (dynamic form to request multiple authors in case there are more than one)
        - Name
        - Biography
    - Classifications (static list of classifications that can be multiple-selected by the user without repeat them)
- Add a button to submit
- Remove the html view from the navigation bar menu
- Add the necessary Javascript code to the search engine to load a button/link that points this view.

**NOTE:** This issue does only the view (html/css) and the JS code is only to add view functionality.

**Comment by andrewbash** [comment]
I can take care of this.
For clarification - shall I go off the style used in the index.html file?

**Comment by MarceStarlet** [comment]
@andrewbash thanks for the help, the answer to your question is yes, you must use the same style as index.html

**Comment by MarceStarlet** [comment]
This is fixed, thanks for the contribution 🥇
